color0 #5b6672
color1 #b07d7d
color2 #88a083
color3 #b79d73
color4 #6e8faf
color5 #8c99b0
color6 #7fa2a8
color7 #d8dee6
color8 #7a8592
color9 #c39191
color10 #9bb295
color11 #cab387
color12 #88a7c5
color13 #a3b2c8
color14 #97b8be
color15 #f1f4f6

cursor                #a7bacd
cursor_text_color     #242a30
background            #242a30
foreground            #d8dee6
selection_foreground  #d8dee6
selection_background  #465362
active_border_color   #6e8faf
inactive_border_color #2e353d
url_color             #6e8faf

active_tab_foreground   #f2f5f7
active_tab_background   #6e8faf
inactive_tab_foreground #aeb7c2
inactive_tab_background #2e353d
cursor_trail_color      #aeb7c2
