background              #242A30
foreground              #D8DEE6

selection_background    #465362
selection_foreground    #F1F4F6

cursor                  #A7BACD
cursor_text_color       #242A30

color0                  #5B6672
color1                  #B07D7D
color2                  #88A083
color3                  #B79D73
color4                  #6E8FAF
color5                  #8C99B0
color6                  #7FA2A8
color7                  #D8DEE6

color8                  #7A8592
color9                  #C39191
color10                 #9BB295
color11                 #CAB387
color12                 #88A7C5
color13                 #A3B2C8
color14                 #97B8BE
color15                 #F1F4F6
